const actionTypes = {
  GET_ALL_MENUS_REQUEST: "GET_ALL_MENUS_REQUEST",
  GET_ALL_MENUS_RECIVIED: "GET_ALL_MENUS_RECIVIED",
  GET_EDIT_CATEGORY_REQUEST: "GET_EDIT_CATEGORY_REQUEST",
  GET_EDIT_CATEGORY_RECIVIED: "GET_EDIT_CATEGORY_RECIVIED",
  GET_EDIT_CATEGORY_ITEM_REQUEST: "GET_EDIT_CATEGORY_ITEM_REQUEST",
  GET_EDIT_CATEGORY_ITEM_RECIVIED: "GET_EDIT_CATEGORY_ITEM_RECIVIED",
};

export default actionTypes;
